/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package servidor_web_socket_turbo_flyer_menu_e_submenu;

import br.com.jmary.home.Home;
import br.com.jmary.utilidades.PopupMenu_Colar;
import java.math.BigDecimal;
import javax.swing.JTextArea;
import servidor_web_socket_turbo_flyer.Servidor_Web_Socket_Turbo_Flyer_01;

/**
 *
 * @author ana
 */
public class Servidor_Web_Socket_Submenu_01 extends javax.swing.JPanel {

    public BigDecimal bigDecimal = new BigDecimal(0);
    String str_bigDecimal;
    
    Home Home;
        
    public Servidor_Web_Socket_Submenu_01( Home Home2 ) {
        Home = Home2;
        str_bigDecimal = String.valueOf( bigDecimal );
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPOpcao_27 = new javax.swing.JPanel();
        tf_Endereco = new javax.swing.JTextField();
        JPOpcao_26 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        bt_Web_Marketing = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btAuto3 = new javax.swing.JButton();
        tf_porta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JPOpcao_28 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        JPOpcao_29 = new javax.swing.JPanel();
        tf_Endereco_Socket_Cliente = new javax.swing.JTextField();

        JPOpcao_27.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_27.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_27MousePressed(evt);
            }
        });

        tf_Endereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseExited(evt);
            }
        });
        tf_Endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_EnderecoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_27Layout = new javax.swing.GroupLayout(JPOpcao_27);
        JPOpcao_27.setLayout(JPOpcao_27Layout);
        JPOpcao_27Layout.setHorizontalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_27Layout.setVerticalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_27Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPOpcao_26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_26.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_26MousePressed(evt);
            }
        });

        jLabel80.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("Link do Marketing: ");

        javax.swing.GroupLayout JPOpcao_26Layout = new javax.swing.GroupLayout(JPOpcao_26);
        JPOpcao_26.setLayout(JPOpcao_26Layout);
        JPOpcao_26Layout.setHorizontalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        JPOpcao_26Layout.setVerticalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jToolBar2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setPreferredSize(new java.awt.Dimension(658, 71));

        jSeparator11.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator11);

        bt_Web_Marketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/Estrtutura_de_Dados.png"))); // NOI18N
        bt_Web_Marketing.setText("Servidor Web");
        bt_Web_Marketing.setFocusable(false);
        bt_Web_Marketing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Web_Marketing.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_Web_Marketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_Web_MarketingMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_Web_MarketingMousePressed(evt);
            }
        });
        jToolBar2.add(bt_Web_Marketing);

        jSeparator8.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator8);

        btAuto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/som.png"))); // NOI18N
        btAuto3.setToolTipText("Cliente Java");
        btAuto3.setBorder(null);
        btAuto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAuto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAuto3MousePressed(evt);
            }
        });

        tf_porta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_porta.setText("8000");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Porta:");

        JPOpcao_28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_28.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_28MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_28MousePressed(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel81.setText("Endereço: ");

        javax.swing.GroupLayout JPOpcao_28Layout = new javax.swing.GroupLayout(JPOpcao_28);
        JPOpcao_28.setLayout(JPOpcao_28Layout);
        JPOpcao_28Layout.setHorizontalGroup(
            JPOpcao_28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );
        JPOpcao_28Layout.setVerticalGroup(
            JPOpcao_28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_29.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_29.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_29MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_29MousePressed(evt);
            }
        });

        tf_Endereco_Socket_Cliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco_Socket_Cliente.setText(" http://localhost:8000");
        tf_Endereco_Socket_Cliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco_Socket_Cliente.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco_Socket_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_Endereco_Socket_ClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_Endereco_Socket_ClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_Endereco_Socket_ClienteMouseExited(evt);
            }
        });
        tf_Endereco_Socket_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_Endereco_Socket_ClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_29Layout = new javax.swing.GroupLayout(JPOpcao_29);
        JPOpcao_29.setLayout(JPOpcao_29Layout);
        JPOpcao_29Layout.setHorizontalGroup(
            JPOpcao_29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco_Socket_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_29Layout.setVerticalGroup(
            JPOpcao_29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_29Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco_Socket_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAuto3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPOpcao_28, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPOpcao_29, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAuto3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPOpcao_29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPOpcao_28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
     
    boolean iniciado = false;
    private void bt_Web_MarketingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Web_MarketingMousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep(1);
             
            if( iniciado == false ){
                iniciado = true;
                bt_Web_Marketing.setEnabled(false);
                
                int porta = Integer.parseInt( tf_porta.getText().trim() );
            
                JTextArea jTextArea_01 = new javax.swing.JTextArea();
                Home.adicionar_Tela_De_Trabalho( "Servidor Web Socket", jTextArea_01 ); 
            
                Servidor_Web_Socket_Turbo_Flyer_01 Servidor_Web_JMarySystems = new Servidor_Web_Socket_Turbo_Flyer_01( porta, jTextArea_01 );
            }
        } catch( Exception e ){ } } }.start();  
    }//GEN-LAST:event_bt_Web_MarketingMousePressed

    private void bt_Web_MarketingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Web_MarketingMouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_bt_Web_MarketingMouseEntered

    private void JPOpcao_26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseEntered

    private void JPOpcao_26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseExited

    private void JPOpcao_26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MousePressed

    PopupMenu_Colar PopupMenu_Colar;
    private void tf_EnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseClicked
        try{
            PopupMenu_Colar = new PopupMenu_Colar(tf_Endereco);
        } catch( Exception e ){}
    }//GEN-LAST:event_tf_EnderecoMouseClicked

    private void tf_EnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoMouseEntered

    private void tf_EnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoMouseExited

    private void tf_EnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_EnderecoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoKeyReleased

    private void JPOpcao_27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseEntered

    private void JPOpcao_27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseExited

    private void JPOpcao_27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MousePressed

    private void btAuto3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAuto3MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep(1);
             
            //Socket_Cliente Socket_Cliente = new Socket_Cliente( Home );
            //Home.adicionar_Tela_De_Trabalho( "Cliente Java", Socket_Cliente ); 

        } catch( Exception e ){ } } }.start(); 
    }//GEN-LAST:event_btAuto3MousePressed

    private void JPOpcao_28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MouseEntered

    private void JPOpcao_28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MouseExited

    private void JPOpcao_28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MousePressed

    private void tf_Endereco_Socket_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco_Socket_ClienteMouseClicked
        try{
            PopupMenu_Colar = new PopupMenu_Colar(tf_Endereco_Socket_Cliente);
        } catch( Exception e ){}
    }//GEN-LAST:event_tf_Endereco_Socket_ClienteMouseClicked

    private void tf_Endereco_Socket_ClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco_Socket_ClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco_Socket_ClienteMouseEntered

    private void tf_Endereco_Socket_ClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco_Socket_ClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco_Socket_ClienteMouseExited

    private void tf_Endereco_Socket_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_Endereco_Socket_ClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco_Socket_ClienteKeyReleased

    private void JPOpcao_29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MouseEntered

    private void JPOpcao_29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MouseExited

    private void JPOpcao_29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPOpcao_26;
    private javax.swing.JPanel JPOpcao_27;
    private javax.swing.JPanel JPOpcao_28;
    private javax.swing.JPanel JPOpcao_29;
    public javax.swing.JButton btAuto3;
    public javax.swing.JButton bt_Web_Marketing;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JTextField tf_Endereco;
    public javax.swing.JTextField tf_Endereco_Socket_Cliente;
    public javax.swing.JTextField tf_porta;
    // End of variables declaration//GEN-END:variables
}
